#!/usr/bin/env bash
ip=$(grep -oE '([0-9]{1,3}.){3}[0-9]{1,3}' <<< $1)

url="http://ip.taobao.com/service/getIpInfo.php?ip=$ip"
ret=$(curl -s $url | jq .data) 
info_=$(jq '.country, .city, .county, .isp' <<< $ret)
info=$(sed s/\"//g <<< $info_)

echo "==>> $info"
